name: Python tests

on:
  pull_request:
    branches: 
      - master
  push:
    tags: v.*
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Test with tox
      run: |
        PYENV=${{ matrix.python-version }}
        tox -e py${PYENV/./}
      if: matrix['python-version'] != '3.8'
    - name: Additional checks with tox
      run: |
        tox -e cov,static,docs
      if: matrix['python-version'] == '3.8'
    - name: Upload coverage results
      run: |
        set -x
        pip install coveralls
        if test -n ${COVERALLS_REPO_TOKEN}; then coveralls; fi
      if: matrix['python-version'] == '3.8'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
