name: Release to PyPI

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build distributions
      run: |
        python ./setup.py sdist bdist_wheel
    - name: Upload to PyPI
      run: |
        twine -u __token__ upload dist/*
      env:
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

